### ISSUE TITLE
bad email formatting

### ISSUE THREAD

**Issue by komuW** [mattiasgeniar/CronWeekly.com#4]
## Getting started

Please fill in the following information.

1. komu:
2. N?A:

This is not about ADVERTISING

Hi, 
The last two issues(issue 75 and 76) of cronWeekly that I've gotten via email are badly formatted. 
I'm using latest chrome on ubuntu 16.04 using gmail.com using basic html version. 

Attached is a screenshot of the formatting.
![formatting](https://cloud.githubusercontent.com/assets/5163857/25128943/963ff3d0-2444-11e7-90fa-0d8fe0d7af52.png)

**Comment by mattiasgeniar** [comment]
Interesting, that shouldn't happen! Looking into it. Thx for the feedback!

**Comment by mattiasgeniar** [comment]
I changed the formatting in previous 2 issues, how did that work out for you? Was it better?

**Comment by komuW** [comment]
Hi,

I noticed the change. Everything works okay now.

Thanks,
Komu W.

**Comment by mattiasgeniar** [comment]
great!
